### ISSUE TITLE
prebuilt keeps on rebooting

### ISSUE THREAD

**Issue by ric96** [xapp-le/SnappyUbuntuCore#1]
UART output: http://paste.ubuntu.com/13525191/

**Comment by ric96** [comment]
if i compile from source, it doesn't even boot at all.

**Comment by woodrow-shen** [comment]
@ric96, I fixed the kernel oops and the prebuild image also was tested to boot. Thanks your report:)

**Comment by ric96** [comment]
thnx, that works well.
