### ISSUE TITLE
snappy: Command not found

### ISSUE THREAD

**Issue by hunanchenxingyu** [xapp-le/SnappyUbuntuCore#2]
Hi,
I use the project on the ubuntu 16.04, and pre-installed some software which be mentioned at README. However, it run failed when i run the command "make gadget", as follows:

> snappy build gadget
> make[1]: snappy: Command not found
> gadget.mk:29: recipe for target 'snappy' failed
> make[1]: **\* [snappy] Error 127
> make[1]: Leaving directory '/home/SnappyUbuntuCore/builder'
> Makefile:21: recipe for target 'build-gadget' failed
> make: **\* [build-gadget] Error 2

**Comment by jamiedbennett** [comment]
snappy has changed to snap in 16.04 and later.

**Comment by hunanchenxingyu** [comment]
Ok.
But how should I use the command "snap" to replace with the "snappy" in the SnappyUbuntuCore/builder/gadget.mk, and the "snap" command didn't support the option "build". Thanks

**Comment by woodrow-shen** [comment]
Hi,
I just changed gadget.mk to fix some issues which are about uboot and gadget snap building. And now building gadget snap depends on snapcraft. So you have to install snapcraft tool.

**Comment by woodrow-shen** [comment]
Just now I verified the image for ubuntu-core 16 can run successfully on roseapple-pi board.

**Comment by hunanchenxingyu** [comment]
Thanks for your information
